package infrastructure

const DEFAULT_MAX_CONNECTIONS = 8
const DEFAULT_MAX_QUEUED_CONNECTIONS = DEFAULT_MAX_CONNECTIONS
const DEFAULT_MAX_QUEUED_SERVER_JOBS = 128
const DEFAULT_MAX_QUEUED_CLIENT_JOBS = 32
const DEFAULT_ADDRESS = "localhost"
const DEFAULT_PORT = 10000
const DEFAULT_CLIENT_FOLDER = "/client_root"
const DEFAULT_QUEUE_SIZE_BYTES = (1024 * 64) - 1 // 64 KB
const DEFAULT_TIMEOUT_MS = 100
