package infrastructure

const (
	DEFAULT_MAX_CONNECTIONS        = 8
	DEFAULT_MAX_QUEUED_CONNECTIONS = DEFAULT_MAX_CONNECTIONS
	DEFAULT_MAX_QUEUED_SERVER_JOBS = 128
	DEFAULT_MAX_QUEUED_CLIENT_JOBS = 32
	DEFAULT_QUEUE_SIZE_BYTES       = (1024 * 64) - 1 // 64 KB
	DEFAULT_READ_TIMEOUT_MS        = 100
)
