package infrastructure

const DEFAULT_MAX_CONNECTIONS = 8
const DEFAULT_MAX_QUEUED_CONNECTIONS = DEFAULT_MAX_CONNECTIONS
const DEFAULT_MAX_QUEUED_SERVER_JOBS = 128
const DEFAULT_MAX_QUEUED_CLIENT_JOBS = 32
const DEFAULT_ADDRESS = "localhost"
const DEFAULT_PORT = 10000
const DEFAULT_CLIENT_FOLDER = "/client_root"
